# Script to convert txt files into FITS files
import numpy as np
import sys
import subprocess as s
from astropy.io import fits
from astropy.table import Table

wd = '/Users/alberto/Desktop/XBOOTES/'

where = '/Users/alberto/Downloads/drive-download-20200225T104432Z-001/'
name = 'Bootes_Ks_2014a_Idet_32_33.phot'
out_name = name[:-5]+'.fits'

cols = ('X_IMAGE','Y_IMAGE','ALPHA_J2000','DELTA_J2000','FLUX_APER_1','FLUX_APER_2','FLUX_APER_3','FLUX_APER_4','FLUX_APER_5','FLUX_APER_6','FLUX_APER_7','FLUX_APER_8','FLUX_APER_9','FLUX_APER_10','FLUX_APER_15','FLUX_APER_20','FLUXERR_APER_1','FLUXERR_APER_2','FLUXERR_APER_3','FLUXERR_APER_4','FLUXERR_APER_5','FLUXERR_APER_6','FLUXERR_APER_7','FLUXERR_APER_8','FLUXERR_APER_9','FLUXERR_APER_10','FLUXERR_APER_15','FLUXERR_APER_20','MAG_APER_1','MAG_APER_2','MAG_APER_3','MAG_APER_4','MAG_APER_5','MAG_APER_6','MAG_APER_7','MAG_APER_8','MAG_APER_9','MAG_APER_10','MAG_APER_15','MAG_APER_20','MAGERR_APER_1','MAGERR_APER_2','MAGERR_APER_3','MAGERR_APER_4','MAGERR_APER_5','MAGERR_APER_6','MAGERR_APER_7','MAGERR_APER_8','MAGERR_APER_9','MAGERR_APER_10','MAGERR_APER_15','MAGERR_APER_20','FLUX_PSF_1','FLUX_PSF_2','FLUX_PSF_3','FLUX_PSF_4','FLUX_PSF_5','FLUX_PSF_6','FLUX_PSF_7','FLUX_PSF_8','FLUX_PSF_9','FLUX_PSF_10','FLUX_PSF_15','FLUX_PSF_20','FLUXERR_PSF_1','FLUXERR_PSF_2','FLUXERR_PSF_3','FLUXERR_PSF_4','FLUXERR_PSF_5','FLUXERR_PSF_6','FLUXERR_PSF_7','FLUXERR_PSF_8','FLUXERR_PSF_9','FLUXERR_PSF_10','FLUXERR_PSF_15','FLUXERR_PSF_20','MAG_PSF_1','MAG_PSF_2','MAG_PSF_3','MAG_PSF_4','MAG_PSF_5','MAG_PSF_6','MAG_PSF_7','MAG_PSF_8','MAG_PSF_9','MAG_PSF_10','MAG_PSF_15','MAG_PSF_20','MAGERR_PSF_1','MAGERR_PSF_2','MAGERR_PSF_3','MAGERR_PSF_4','MAGERR_PSF_5','MAGERR_PSF_6','MAGERR_PSF_7','MAGERR_PSF_8','MAGERR_PSF_9','MAGERR_PSF_10','MAGERR_PSF_15','MAGERR_PSF_20','BACKGROUND','IMAFLAGS_APER_1','IMAFLAGS_APER_2','IMAFLAGS_APER_3','IMAFLAGS_APER_4','IMAFLAGS_APER_5','IMAFLAGS_APER_6','IMAFLAGS_APER_7','IMAFLAGS_APER_8','IMAFLAGS_APER_9','IMAFLAGS_APER_10','IMAFLAGS_APER_15','IMAFLAGS_APER_20','SEGFLAGS_APER_1','SEGFLAGS_APER_2','SEGFLAGS_APER_3','SEGFLAGS_APER_4','SEGFLAGS_APER_5','SEGFLAGS_APER_6','SEGFLAGS_APER_7','SEGFLAGS_APER_8','SEGFLAGS_APER_9','SEGFLAGS_APER_10','SEGFLAGS_APER_15','SEGFLAGS_APER_20','FLAG_SUBFIELD','FLAG_DUPLICATE','IMAGE','OBJNAME')

# Step 1, filter out sources with NULL keyword (one less column, 128 instead of 129)
s.call('grep -vwE "NULL" '+where+name+' > '+where+name[:-5]+'.dat',shell=True)

data1 = np.genfromtxt(where+name[:-5]+'.dat',skip_header=22,dtype=None)

#write catalog
cat=Table(data1.T,names=cols,dtype=None)
cat.write(where+out_name,format='fits',overwrite=True)